### ISSUE TITLE
Update gapminder csvs into zipfile 

### ISSUE THREAD

**Issue by kristi-sara** [UCSBCarpentry/2021-05-06-IntroR#1]
nordic country data
nordic country data 2
gapminder data 

are the 2 csv files for the Intro R workshop. Should be wrapped into a zipfile and added to the setup page instead of floating in episode 2 project intro 
https://jonjab.github.io/r-intro-geospatial/02-project-intro/index.html

**Comment by torwhite** [comment]
done in this repo. Should check in GeoR too.
